"""
Configuration package for BullBoard application
Contains all constants, styling, and configuration settings
"""

from .constants import (
    CUSTOM_CSS,
    SYMBOL_TO_NAME_MAPPING,
    SECTOR_MAPPING,
    DEFAULT_SELECTED_SECTORS,
    DEFAULT_STOCKS_PER_SECTOR,
    ITEMS_PER_PAGE
)

from .settings import (
    HIGH_RISK_THRESHOLD,
    MODERATE_RISK_THRESHOLD,
    LOW_RISK_THRESHOLD,
    EXCELLENT_RETURN_THRESHOLD,
    STRONG_RETURN_THRESHOLD,
    GOOD_RETURN_THRESHOLD,
    MIN_DAYS_NEEDED,
    ROLLING_WINDOW_DAYS,
    MAX_DRAWDOWN_DAYS,
    CHART_HEIGHT,
    CHART_COLOR_SCHEME,
    DEFAULT_CHART_COLORS,
    PERFORMANCE_CHART_HEIGHT,
    CORRELATION_HEATMAP_HEIGHT,
    DEBUG_MODE,
    DEBUG_TICKERS,
    BATCH_SIZE,
    DELAY_BETWEEN_BATCHES
)

__version__ = "1.0.0"

# Make everything available at package level
__all__ = [
    'CUSTOM_CSS',
    'SYMBOL_TO_NAME_MAPPING', 
    'SECTOR_MAPPING',
    'DEFAULT_SELECTED_SECTORS',
    'DEFAULT_STOCKS_PER_SECTOR',
    'ITEMS_PER_PAGE',
    'HIGH_RISK_THRESHOLD',
    'MODERATE_RISK_THRESHOLD',
    'LOW_RISK_THRESHOLD',
    'EXCELLENT_RETURN_THRESHOLD',
    'STRONG_RETURN_THRESHOLD', 
    'GOOD_RETURN_THRESHOLD',
    'MIN_DAYS_NEEDED',
    'ROLLING_WINDOW_DAYS',
    'MAX_DRAWDOWN_DAYS',
    'CHART_HEIGHT',
    'CHART_COLOR_SCHEME',
    'DEFAULT_CHART_COLORS',
    'PERFORMANCE_CHART_HEIGHT',
    'CORRELATION_HEATMAP_HEIGHT',
    'DEBUG_MODE',
    'DEBUG_TICKERS',
    'BATCH_SIZE',
    'DELAY_BETWEEN_BATCHES'
]
